language: node_js
node_js:
  - "10"

branches:
  only:
    - master

before_script:
  - npm install firebase-tools
  - npm install
  - npx gatsby build

script:
  - firebase deploy --token "$FIREBASE_TOKEN"
after_success:

notifications:
  email:
    on_failure: kittiphat.s@theiconweb.com
    on_success: kittiphat.s@theiconweb.com
